name: cmeyf-cuda13
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipywidgets
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cupy